name: Deploy to mvukic.github.io

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install and build
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        run: |
          yarn
          yarn build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        BRANCH: master
        FOLDER: dist/mvukic-github-io
        REPOSITORY_NAME: mvukic/mvukic.github.io